default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin1
  password: Amir@!-23545
  host: localhost

development:
  <<: *default
  database: crypto_arbitrage_development

test:
  <<: *default
  database: crypto_arbitrage_test

production:
  adapter: postgresql
  encoding: unicode
  database: crypto_arbitrage_production
  username: admin1
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432
